export const errConstants = {
    GET_USERS_ERROR: 'GET_USERS_ERROR',
    LOGIN_ERROR: 'LOGIN_ERROR',
    GET_USER_ROLES_ERROR: 'GET_USER_ROLES_ERROR',
    GET_DEPARTMENTS_ERROR: 'GET_DEPARTMENTS_ERROR',
    CREATE_DEPARTMENTS_ERROR: 'CREATE_DEPARTMENTS_ERROR',
    DELETE_DEPARTMENTS_ERROR: 'DELETE_DEPARTMENTS_ERROR'
};