export const userConstants = {
    GET_USER_ROLES_SUCCESS: 'GET_USER_ROLES_SUCCESS',
    GET_LINK_OF_ROLE_SUCCESS: 'GET_LINK_OF_ROLE_SUCCESS',
    SET_ROLE_SUCCESS: 'SET_ROLE_SUCCESS',

    GETROLE_SAMEDEPARTMENT_REQUEST: 'GETROLE_SAMEDEPARTMENT_REQUEST',
    GETROLE_SAMEDEPARTMENT_SUCCESS: 'GETROLE_SAMEDEPARTMENT_SUCCESS',
    GETROLE_SAMEDEPARTMENT_FAILURE: 'GETROLE_SAMEDEPARTMENT_FAILURE',

    GETALLUSER_OFDEPARTMENT_REQUEST: 'GETALLUSER_OFDEPARTMENT_REQUEST',
    GETALLUSER_OFDEPARTMENT_SUCCESS: 'GETALLUSER_OFDEPARTMENT_SUCCESS',
    GETALLUSER_OFDEPARTMENT_FAILURE: 'GETALLUSER_OFDEPARTMENT_FAILURE',

    GETALLUSER_SAMEDEPARTMENT_REQUEST: 'GETALLUSER_SAMEDEPARTMENT_REQUEST',
    GETALLUSER_SAMEDEPARTMENT_SUCCESS: 'GETALLUSER_SAMEDEPARTMENT_SUCCESS',
    GETALLUSER_SAMEDEPARTMENT_FAILURE: 'GETALLUSER_SAMEDEPARTMENT_FAILURE',

    GETALLUSER_OFCOMPANY_REQUEST: 'GETALLUSER_OFCOMPANY_REQUEST',
    GETALLUSER_OFCOMPANY_SUCCESS: 'GETALLUSER_OFCOMPANY_SUCCESS',
    GETALLUSER_OFCOMPANY_FAILURE: 'GETALLUSER_OFCOMPANY_FAILURE',
};