export const userConstants = {
    GET_USER_ROLES_SUCCESS: 'GET_USER_ROLES_SUCCESS',
    GET_LINK_OF_ROLE_SUCCESS: 'GET_LINK_OF_ROLE_SUCCESS',
    SET_ROLE_SUCCESS: 'SET_ROLE_SUCCESS',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
};