export const departmentConstants = {
    GETALL_REQUEST: 'DEPARTMENT_GETALL_REQUEST',
    GETALL_SUCCESS: 'DEPARTMENT_GETALL_SUCCESS',
    GETALL_FAILURE: 'DEPARTMENT_GETALL_FAILURE',

    GETDEPARTMENT_OFUSER_REQUEST: 'GETDEPARTMENT_OFUSER_REQUEST',
    GETDEPARTMENT_OFUSER_SUCCESS: 'GETDEPARTMENT_OFUSER_SUCCESS',
    GETDEPARTMENT_OFUSER_FAILURE: 'GETDEPARTMENT_OFUSER_FAILURE',
};