export const employeeConstants = {
    GETALL_REQUEST: 'EMPLOYEE_GETALL_REQUEST',
    GETALL_SUCCESS: 'EMPLOYEE_GETALL_SUCCESS',
    GETALL_FAILURE: 'EMPLOYEE_GETALL_FAILURE',

    GETINFORMATIONEMPLOYEE_REQUEST: 'EMPLOYEE_GET_INFORMATION_EMPLOYEE_REQUEST',
    GETINFORMATIONEMPLOYEE_SUCCESS: 'EMPLOYEE_GET_INFORMATION_EMPLOYEE_SUCCESS',
    GETINFORMATIONEMPLOYEE_FAILURE: 'EMPLOYEE_GET_INFORMATION_EMPLOYEE_FAILURE',

    GETLIST_EMPLOYEE_REQUEST: 'EMPLOYEE_GET_LIST_EMPLOYEE_REQUEST',
    GETLIST_EMPLOYEE_SUCCESS: 'EMPLOYEE_GET_LIST_EMPLOYEE_SUCCESS',
    GETLIST_EMPLOYEE_FAILURE: 'EMPLOYEE_GET_LIST_EMPLOYEE_FAILURE',

    ADDEMPLOYEE_REQUEST: 'EMPLOYEE_ADDEMPLOYEE_REQUEST',
    ADDEMPLOYEE_SUCCESS: 'EMPLOYEE_ADDEMPLOYEE_SUCCESS',
    ADDEMPLOYEE_FAILURE: 'EMPLOYEE_ADDEMPLOYEE_FAILURE',

    UPDATE_INFORMATION_REQUEST: 'EMPLOYEE_UPDATE_INFORMATION_REQUEST',
    UPDATE_INFORMATION_SUCCESS: 'EMPLOYEE_UPDATE_INFORMATION_SUCCESS',
    UPDATE_INFORMATION_FAILURE: 'EMPLOYEE_UPDATE_INFORMATION_FAILURE',



};