export const kpiPersonalConstants = {
    GETALL_REQUEST: 'KPIPERSONAL_GETALL_REQUEST',
    GETALL_SUCCESS: 'KPIPERSONAL_GETALL_SUCCESS',
    GETALL_FAILURE: 'KPIPERSONAL_GETALL_FAILURE',

    GETALLTARGET_BYIDUSER_REQUEST: 'KPIPERSONAL_GETALLTARGET_BYIDUSER_REQUEST',
    GETALLTARGET_BYIDUSER_SUCCESS: 'KPIPERSONAL_GETALLTARGET_BYIDUSER_SUCCESS',
    GETALLTARGET_BYIDUSER_FAILURE: 'KPIPERSONAL_GETALLTARGET_BYIDUSER_FAILURE',

    GETALL_PARENTTARGET_REQUEST: 'KPIPERSONAL_GETALL_PARENTTARGET_REQUEST',
    GETALL_PARENTTARGET_SUCCESS: 'KPIPERSONAL_GETALL_PARENTTARGET_SUCCESS',
    GETALL_PARENTTARGET_FAILURE: 'KPIPERSONAL_GETALL_PARENTTARGET_FAILURE',

    GETTARGET_BYID_REQUEST: 'KPIPERSONAL_GETTARGET_BYID_REQUEST',
    GETTARGET_BYID_SUCCESS: 'KPIPERSONAL_GETTARGET_BYID_SUCCESS',
    GETTARGET_BYID_FAILURE: 'KPIPERSONAL_GETTARGET_BYID_FAILURE',

    ADDTARGET_REQUEST: 'KPIPERSONAL_ADDTARGET_REQUEST',
    ADDTARGET_SUCCESS: 'KPIPERSONAL_ADDTARGET_SUCCESS',
    ADDTARGET_FAILURE: 'KPIPERSONAL_ADDTARGET_FAILURE',

    EDITTARGET_REQUEST: 'KPIPERSONAL_EDITTARGET_REQUEST',
    EDITTARGET_SUCCESS: 'KPIPERSONAL_EDITTARGET_SUCCESS',
    EDITTARGET_FAILURE: 'KPIPERSONAL_EDITTARGET_FAILURE',

    DELETETARGET_REQUEST: 'KPIPERSONAL_DELETETARGET_REQUEST',
    DELETETARGET_SUCCESS: 'KPIPERSONAL_DELETETARGET_SUCCESS',
    DELETETARGET_FAILURE: 'KPIPERSONAL_DELETETARGET_FAILURE',

    CONFIRM_REQUEST: 'KPIPERSONAL_CONFIRM_REQUEST',
    CONFIRM_SUCCESS: 'KPIPERSONAL_CONFIRM_SUCCESS',
    CONFIRM_FAILURE: 'KPIPERSONAL_CONFIRM_FAILURE',

    APPROVE_REQUEST: 'KPIPERSONAL_APPROVE_REQUEST',
    APPROVE_SUCCESS: 'KPIPERSONAL_APPROVE_SUCCESS',
    APPROVE_FAILURE: 'KPIPERSONAL_APPROVE_FAILURE',

    REQUEST_EDITKPI_REQUEST: 'KPIPERSONAL_REQUEST_EDITKPI_REQUEST',
    REQUEST_EDITKPI_SUCCESS: 'KPIPERSONAL_REQUEST_EDITKPI_SUCCESS',
    REQUEST_EDITKPI_FAILURE: 'KPIPERSONAL_REQUEST_EDITKPI_FAILURE',
};