export const kpiPersonalConstants = {
    GETALL_KPIPERSONAL_OfUNIT_REQUEST: 'GETALL_KPIPERSONAL_OfUNIT_REQUEST',
    GETALL_KPIPERSONAL_OfUNIT_SUCCESS: 'GETALL_KPIPERSONAL_OfUNIT_SUCCESS',
    GETALL_KPIPERSONAL_OfUNIT_FAILURE: 'GETALL_KPIPERSONAL_OfUNIT_FAILURE',
    
    GETALL_KPIPERSONAL_REQUEST: 'GETALL_KPIPERSONAL_REQUEST',
    GETALL_KPIPERSONAL_SUCCESS: 'GETALL_KPIPERSONAL_SUCCESS',
    GETALL_KPIPERSONAL_FAILURE: 'GETALL_KPIPERSONAL_FAILURE',

    GET_KPIPERSONAL_BYID_REQUEST: 'GET_KPIPERSONAL_BYID_REQUEST',
    GET_KPIPERSONAL_BYID_SUCCESS: 'GET_KPIPERSONAL_BYID_SUCCESS',
    GET_KPIPERSONAL_BYID_FAILURE: 'GET_KPIPERSONAL_BYID_FAILURE',

    GET_KPIPERSONAL_BYMONTH_REQUEST: 'GET_KPIPERSONAL_BYMONTH_REQUEST',
    GET_KPIPERSONAL_BYMONTH_SUCCESS: 'GET_KPIPERSONAL_BYMONTH_SUCCESS',
    GET_KPIPERSONAL_BYMONTH_FAILURE: 'GET_KPIPERSONAL_BYMONTH_FAILURE',
    
    GETCURRENT_KPIPERSONAL_REQUEST: 'GETCURRENT_KPIPERSONAL_REQUEST',
    GETCURRENT_KPIPERSONAL_SUCCESS: 'GETCURRENT_KPIPERSONAL_SUCCESS',
    GETCURRENT_KPIPERSONAL_FAILURE: 'GETCURRENT_KPIPERSONAL_FAILURE',

    ADD_KPIPERSONAL_REQUEST: 'ADD_KPIPERSONAL_REQUEST',
    ADD_KPIPERSONAL_SUCCESS: 'ADD_KPIPERSONAL_SUCCESS',
    ADD_KPIPERSONAL_FAILURE: 'ADD_KPIPERSONAL_FAILURE',

    EDIT_KPIPERSONAL_REQUEST: 'EDIT_KPIPERSONAL_REQUEST',
    EDIT_KPIPERSONAL_SUCCESS: 'EDIT_KPIPERSONAL_SUCCESS',
    EDIT_KPIPERSONAL_FAILURE: 'EDIT_KPIPERSONAL_FAILURE',

    EDITSTATUS_KPIPERSONAL_REQUEST: 'EDITSTATUS_KPIPERSONAL_REQUEST',
    EDITSTATUS_KPIPERSONAL_SUCCESS: 'EDITSTATUS_KPIPERSONAL_SUCCESS',
    EDITSTATUS_KPIPERSONAL_FAILURE: 'EDITSTATUS_KPIPERSONAL_FAILURE',

    APPROVE_KPIPERSONAL_REQUEST: 'APPROVE_KPIPERSONAL_REQUEST',
    APPROVE_KPIPERSONAL_SUCCESS: 'APPROVE_KPIPERSONAL_SUCCESS',
    APPROVE_KPIPERSONAL_FAILURE: 'APPROVE_KPIPERSONAL_FAILURE',

    EVALUATETARGET_KPIPERSONAL_REQUEST: 'EVALUATETARGET_KPIPERSONAL_REQUEST',
    EVALUATETARGET_KPIPERSONAL_SUCCESS: 'EVALUATETARGET_KPIPERSONAL_SUCCESS',
    EVALUATETARGET_KPIPERSONAL_FAILURE: 'EVALUATETARGET_KPIPERSONAL_FAILURE',

    DELETE_KPIPERSONAL_REQUEST: 'DELETE_KPIPERSONAL_REQUEST',
    DELETE_KPIPERSONAL_SUCCESS: 'DELETE_KPIPERSONAL_SUCCESS',
    DELETE_KPIPERSONAL_FAILURE: 'DELETE_KPIPERSONAL_FAILURE',

    ADDTARGET_KPIPERSONAL_REQUEST: 'ADDTARGET_KPIPERSONAL_REQUEST',
    ADDTARGET_KPIPERSONAL_SUCCESS: 'ADDTARGET_KPIPERSONAL_SUCCESS',
    ADDTARGET_KPIPERSONAL_FAILURE: 'ADDTARGET_KPIPERSONAL_FAILURE',

    EDITTARGET_KPIPERSONAL_REQUEST: 'EDITTARGET_KPIPERSONAL_REQUEST',
    EDITTARGET_KPIPERSONAL_SUCCESS: 'EDITTARGET_KPIPERSONAL_SUCCESS',
    EDITTARGET_KPIPERSONAL_FAILURE: 'EDITTARGET_KPIPERSONAL_FAILURE',

    EDITSTATUS_TARGET_KPIPERSONAL_REQUEST: 'EDITSTATUS_TARGET_KPIPERSONAL_REQUEST',
    EDITSTATUS_TARGET_KPIPERSONAL_SUCCESS: 'EDITSTATUS_TARGET_KPIPERSONAL_SUCCESS',
    EDITSTATUS_TARGET_KPIPERSONAL_FAILURE: 'EDITSTATUS_TARGET_KPIPERSONAL_FAILURE',

    DELETETARGET_KPIPERSONAL_REQUEST: 'DELETETARGET_KPIPERSONAL_REQUEST',
    DELETETARGET_KPIPERSONAL_SUCCESS: 'DELETETARGET_KPIPERSONAL_SUCCESS',
    DELETETARGET_KPIPERSONAL_FAILURE: 'DELETETARGET_KPIPERSONAL_FAILURE',
};