export const kpiUnitConstants = {
    GETALL_REQUEST: 'KPIUNIT_GETALL_REQUEST',
    GETALL_SUCCESS: 'KPIUNIT_GETALL_SUCCESS',
    GETALL_FAILURE: 'KPIUNIT_GETALL_FAILURE',

    GETALLTARGET_BYIDUNIT_REQUEST: 'KPIUNIT_GETALLTARGET_BYIDUNIT_REQUEST',
    GETALLTARGET_BYIDUNIT_SUCCESS: 'KPIUNIT_GETALLTARGET_BYIDUNIT_SUCCESS',
    GETALLTARGET_BYIDUNIT_FAILURE: 'KPIUNIT_GETALLTARGET_BYIDUNIT_FAILURE',

    GETTARGET_BYID_REQUEST: 'KPIUNIT_GETTARGET_BYID_REQUEST',
    GETTARGET_BYID_SUCCESS: 'KPIUNIT_GETTARGET_BYID_SUCCESS',
    GETTARGET_BYID_FAILURE: 'KPIUNIT_GETTARGET_BYID_FAILURE',

    ADDTARGET_REQUEST: 'KPIUNIT_ADDTARGET_REQUEST',
    ADDTARGET_SUCCESS: 'KPIUNIT_ADDTARGET_SUCCESS',
    ADDTARGET_FAILURE: 'KPIUNIT_ADDTARGET_FAILURE',

    EDITTARGET_REQUEST: 'KPIUNIT_EDITTARGET_REQUEST',
    EDITTARGET_SUCCESS: 'KPIUNIT_EDITTARGET_SUCCESS',
    EDITTARGET_FAILURE: 'KPIUNIT_EDITTARGET_FAILURE',

    DELETETARGET_REQUEST: 'KPIUNIT_DELETETARGET_REQUEST',
    DELETETARGET_SUCCESS: 'KPIUNIT_DELETETARGET_SUCCESS',
    DELETETARGET_FAILURE: 'KPIUNIT_DELETETARGET_FAILURE',

    CONFIRM_REQUEST: 'KPIUNIT_CONFIRM_REQUEST',
    CONFIRM_SUCCESS: 'KPIUNIT_CONFIRM_SUCCESS',
    CONFIRM_FAILURE: 'KPIUNIT_CONFIRM_FAILURE',
};