export const companiesConstants = {
    GET_COMPANIES_REQUEST: 'GET_COMPANIES_REQUEST',
    GET_COMPANIES_SUCCESS: 'GET_COMPANIES_SUCCESS',
    GET_COMPANIES_ERROR: 'GET_COMPANIES_ERROR',

    CREATE_COMPANY_REQUEST: 'CREATE_COMPANY_REQUEST',
    CREATE_COMPANY_SUCCESS: 'CREATE_COMPANY_SUCCESS',
    CREATE_COMPANY_ERROR: 'CREATE_COMPANY_ERROR',

    EDIT_COMPANY_REQUEST: 'EDIT_COMPANY_REQUEST',
    EDIT_COMPANY_SUCCESS: 'EDIT_COMPANY_SUCCESS',
    EDIT_COMPANY_ERROR: 'EDIT_COMPANY_ERROR',
}