export const companiesConstants = {
    GET_COMPANIES_SUCCESS: 'GET_COMPANIES_SUCCESS',
    GET_COMPANIES_ERROR: 'GET_COMPANIES_ERROR',

    CREATE_COMPANY_SUCCESS: 'CREATE_COMPANY_SUCCESS',
    CREATE_COMPANY_ERROR: 'CREATE_COMPANY_ERROR',
}