export const departmentsConstants = {
    GET_DEPARTMENTS_SUCCESS: 'GET_DEPARTMENTS_SUCCESS',
    CREATE_DEPARTMENTS_SUCCESS: 'CREATE_DEPARTMENTS_SUCCESS',
    GET_DEPARTMENT_INFO_SUCCESS: 'GET_DEPARTMENT_INFO_SUCCESS',
    ADD_USER_WITH_ROLE_SUCCESS: 'ADD_USER_WITH_ROLE_SUCCESS',
    DELETE_DEPARTMENT_SUCCESS: 'DELETE_DEPARTMENT_SUCCESS'
}