export const linksConstants = {
    GET_LINKS_SUCCESS: 'GET_LINKS_SUCCESS',
    GET_LINK_INFO_SUCCESS: 'GET_LINK_INFO_SUCCESS',
    CREATE_LINK_SUCCESS: 'CREATE_LINK_SUCCESS',
    ADD_ROLE_TO_LINK_SUCCESS: 'ADD_ROLE_TO_LINK_SUCCESS'
}