export const rolesConstants = {
    GET_ROLES_SUCCESS: 'GET_ROLES_SUCCESS',
    GET_SUPER_ROLE_SUCCESS: 'GET_SUPER_ROLE_SUCCESS',
    GET_ROLE_ADMIN_SUCCESS: 'GET_ROLE_ADMIN_SUCCESS',
    ADD_ADMIN_SUCCESS: 'ADD_ADMIN_SUCCESS'
}